create table public.articles (
  url character varying not null,
  data jsonb null,
  constraint articles_pkey primary key (url)
) TABLESPACE pg_default;

create table public.sources (
  id bigint generated by default as identity not null,
  name character varying null,
  url character varying null,
  constraint sources_pkey primary key (id)
) TABLESPACE pg_default;
