name: Trigger Cron Job Worker

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: data-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt
          .venv/bin/python -m playwright install --with-deps webkit

      - name: Run script
        run: .venv/bin/python main.py
